CREATE TABLE IF NOT EXISTS `__EFMigrationsHistory` (
    `MigrationId` varchar(95) NOT NULL,
    `ProductVersion` varchar(32) NOT NULL,
    CONSTRAINT `PK___EFMigrationsHistory` PRIMARY KEY (`MigrationId`)
);

START TRANSACTION;

CREATE TABLE `Categoria` (
    `Id` char(36) NOT NULL,
    `NomeCategoria` varchar(100) NULL,
    `UsuarioCriacao` varchar(100) NULL,
    `DataCriacao` datetime(6) NOT NULL,
    `UsuarioModificacao` varchar(100) NULL,
    `DataModificacao` datetime(6) NOT NULL,
    CONSTRAINT `PK_Categoria` PRIMARY KEY (`Id`)
);

CREATE TABLE `ENDERECOS` (
    `Id` char(36) NOT NULL,
    `Cep` varchar(8) NOT NULL,
    `Estado` varchar(50) NOT NULL,
    `Cidade` varchar(100) NOT NULL,
    `Bairro` varchar(100) NOT NULL,
    `Logradouro` varchar(200) NOT NULL,
    `Complemento` varchar(250) NULL,
    `Numero` varchar(50) NOT NULL,
    CONSTRAINT `PK_ENDERECOS` PRIMARY KEY (`Id`)
);

CREATE TABLE `FormaPagamento` (
    `Id` char(36) NOT NULL,
    `NomeFormaPagamento` varchar(100) NULL,
    `UsuarioCriacao` varchar(100) NULL,
    `Ativo` tinyint(1) NOT NULL,
    `DataCriacao` datetime(6) NOT NULL,
    `UsuarioModificacao` varchar(100) NULL,
    `DataModificacao` datetime(6) NOT NULL,
    CONSTRAINT `PK_FormaPagamento` PRIMARY KEY (`Id`)
);

CREATE TABLE `PRODUTOS` (
    `Id` char(36) NOT NULL,
    `CategoriaId` char(36) NOT NULL,
    `Marca` varchar(80) NOT NULL,
    `Nome` varchar(80) NOT NULL,
    `Descricao` varchar(80) NULL,
    `UsuarioCriacao` varchar(100) NULL,
    `DataCriacao` datetime(6) NOT NULL,
    `UsuarioModificacao` varchar(100) NULL,
    `DataModificacao` datetime(6) NOT NULL,
    CONSTRAINT `PK_PRODUTOS` PRIMARY KEY (`Id`),
    CONSTRAINT `FK_PRODUTOS_Categoria_CategoriaId` FOREIGN KEY (`CategoriaId`) REFERENCES `Categoria` (`Id`) ON DELETE RESTRICT
);

CREATE TABLE `FORNECEDORES` (
    `Id` char(36) NOT NULL,
    `Nome` varchar(80) NULL,
    `NomeFantasia` varchar(80) NULL,
    `Cnpj` varchar(14) NULL,
    `EnderecoId` char(36) NOT NULL,
    `Ativo` tinyint(1) NOT NULL,
    `UsuarioCriacao` varchar(100) NULL,
    `DataCriacao` datetime(6) NOT NULL,
    `UsuarioModificacao` varchar(100) NULL,
    `DataModificacao` datetime(6) NOT NULL,
    CONSTRAINT `PK_FORNECEDORES` PRIMARY KEY (`Id`),
    CONSTRAINT `FK_FORNECEDORES_ENDERECOS_EnderecoId` FOREIGN KEY (`EnderecoId`) REFERENCES `ENDERECOS` (`Id`) ON DELETE RESTRICT
);

CREATE TABLE `Compra` (
    `Id` char(36) NOT NULL,
    `FornecedorId` char(36) NOT NULL,
    `FormaPagamentoId` char(36) NOT NULL,
    `Compartilhado` tinyint(1) NOT NULL,
    `StatusCompra` int NOT NULL,
    `DataCompra` datetime(6) NOT NULL,
    `UsuarioCriacao` varchar(100) NULL,
    `DataCriacao` datetime(6) NOT NULL,
    `UsuarioModificacao` varchar(100) NULL,
    `DataModificacao` datetime(6) NOT NULL,
    CONSTRAINT `PK_Compra` PRIMARY KEY (`Id`),
    CONSTRAINT `FK_Compra_FormaPagamento_FormaPagamentoId` FOREIGN KEY (`FormaPagamentoId`) REFERENCES `FormaPagamento` (`Id`) ON DELETE RESTRICT,
    CONSTRAINT `FK_Compra_FORNECEDORES_FornecedorId` FOREIGN KEY (`FornecedorId`) REFERENCES `FORNECEDORES` (`Id`) ON DELETE RESTRICT
);

CREATE TABLE `CompraCompartilhada` (
    `Id` char(36) NOT NULL,
    `CompraId` char(36) NOT NULL,
    `UsuariosCompartilhados` varchar(100) NULL,
    `UsuarioCriacao` varchar(100) NULL,
    `DataCriacao` datetime(6) NOT NULL,
    `UsuarioModificacao` varchar(100) NULL,
    `DataModificacao` datetime(6) NOT NULL,
    CONSTRAINT `PK_CompraCompartilhada` PRIMARY KEY (`Id`),
    CONSTRAINT `FK_CompraCompartilhada_Compra_CompraId` FOREIGN KEY (`CompraId`) REFERENCES `Compra` (`Id`) ON DELETE RESTRICT
);

CREATE TABLE `ItmCompra` (
    `Id` char(36) NOT NULL,
    `CompraId` char(36) NOT NULL,
    `ProdutoId` char(36) NOT NULL,
    `Preco` decimal(65,30) NOT NULL,
    `Quantidade` int NOT NULL,
    `Validade` datetime(6) NOT NULL,
    `UsuarioCriacao` varchar(100) NULL,
    `DataCriacao` datetime(6) NOT NULL,
    `UsuarioModificacao` varchar(100) NULL,
    `DataModificacao` datetime(6) NOT NULL,
    CONSTRAINT `PK_ItmCompra` PRIMARY KEY (`Id`),
    CONSTRAINT `FK_ItmCompra_Compra_CompraId` FOREIGN KEY (`CompraId`) REFERENCES `Compra` (`Id`) ON DELETE RESTRICT,
    CONSTRAINT `FK_ItmCompra_PRODUTOS_ProdutoId` FOREIGN KEY (`ProdutoId`) REFERENCES `PRODUTOS` (`Id`) ON DELETE RESTRICT
);

CREATE INDEX `IX_Compra_FormaPagamentoId` ON `Compra` (`FormaPagamentoId`);

CREATE INDEX `IX_Compra_FornecedorId` ON `Compra` (`FornecedorId`);

CREATE UNIQUE INDEX `IX_CompraCompartilhada_CompraId` ON `CompraCompartilhada` (`CompraId`);

CREATE UNIQUE INDEX `IX_FORNECEDORES_EnderecoId` ON `FORNECEDORES` (`EnderecoId`);

CREATE INDEX `IX_ItmCompra_CompraId` ON `ItmCompra` (`CompraId`);

CREATE INDEX `IX_ItmCompra_ProdutoId` ON `ItmCompra` (`ProdutoId`);

CREATE INDEX `IX_PRODUTOS_CategoriaId` ON `PRODUTOS` (`CategoriaId`);

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210705220841_Inicial', '5.0.1');

COMMIT;

START TRANSACTION;

ALTER TABLE `FORNECEDORES` MODIFY COLUMN `Ativo` bit NOT NULL;

ALTER TABLE `Categoria` ADD `Ativo` tinyint(1) NOT NULL DEFAULT FALSE;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210710193138_Categoria', '5.0.1');

COMMIT;

START TRANSACTION;

DROP PROCEDURE IF EXISTS `POMELO_BEFORE_DROP_PRIMARY_KEY`;
DELIMITER //
CREATE PROCEDURE `POMELO_BEFORE_DROP_PRIMARY_KEY`(IN `SCHEMA_NAME_ARGUMENT` VARCHAR(255), IN `TABLE_NAME_ARGUMENT` VARCHAR(255))
BEGIN
	DECLARE HAS_AUTO_INCREMENT_ID TINYINT(1);
	DECLARE PRIMARY_KEY_COLUMN_NAME VARCHAR(255);
	DECLARE PRIMARY_KEY_TYPE VARCHAR(255);
	DECLARE SQL_EXP VARCHAR(1000);
	SELECT COUNT(*)
		INTO HAS_AUTO_INCREMENT_ID
		FROM `information_schema`.`COLUMNS`
		WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
			AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
			AND `Extra` = 'auto_increment'
			AND `COLUMN_KEY` = 'PRI'
			LIMIT 1;
	IF HAS_AUTO_INCREMENT_ID THEN
		SELECT `COLUMN_TYPE`
			INTO PRIMARY_KEY_TYPE
			FROM `information_schema`.`COLUMNS`
			WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
				AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
				AND `COLUMN_KEY` = 'PRI'
			LIMIT 1;
		SELECT `COLUMN_NAME`
			INTO PRIMARY_KEY_COLUMN_NAME
			FROM `information_schema`.`COLUMNS`
			WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
				AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
				AND `COLUMN_KEY` = 'PRI'
			LIMIT 1;
		SET SQL_EXP = CONCAT('ALTER TABLE `', (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA())), '`.`', TABLE_NAME_ARGUMENT, '` MODIFY COLUMN `', PRIMARY_KEY_COLUMN_NAME, '` ', PRIMARY_KEY_TYPE, ' NOT NULL;');
		SET @SQL_EXP = SQL_EXP;
		PREPARE SQL_EXP_EXECUTE FROM @SQL_EXP;
		EXECUTE SQL_EXP_EXECUTE;
		DEALLOCATE PREPARE SQL_EXP_EXECUTE;
	END IF;
END //
DELIMITER ;

DROP PROCEDURE IF EXISTS `POMELO_AFTER_ADD_PRIMARY_KEY`;
DELIMITER //
CREATE PROCEDURE `POMELO_AFTER_ADD_PRIMARY_KEY`(IN `SCHEMA_NAME_ARGUMENT` VARCHAR(255), IN `TABLE_NAME_ARGUMENT` VARCHAR(255), IN `COLUMN_NAME_ARGUMENT` VARCHAR(255))
BEGIN
	DECLARE HAS_AUTO_INCREMENT_ID INT(11);
	DECLARE PRIMARY_KEY_COLUMN_NAME VARCHAR(255);
	DECLARE PRIMARY_KEY_TYPE VARCHAR(255);
	DECLARE SQL_EXP VARCHAR(1000);
	SELECT COUNT(*)
		INTO HAS_AUTO_INCREMENT_ID
		FROM `information_schema`.`COLUMNS`
		WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
			AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
			AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
			AND `COLUMN_TYPE` LIKE '%int%'
			AND `COLUMN_KEY` = 'PRI';
	IF HAS_AUTO_INCREMENT_ID THEN
		SELECT `COLUMN_TYPE`
			INTO PRIMARY_KEY_TYPE
			FROM `information_schema`.`COLUMNS`
			WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
				AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
				AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
				AND `COLUMN_TYPE` LIKE '%int%'
				AND `COLUMN_KEY` = 'PRI';
		SELECT `COLUMN_NAME`
			INTO PRIMARY_KEY_COLUMN_NAME
			FROM `information_schema`.`COLUMNS`
			WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
				AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
				AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
				AND `COLUMN_TYPE` LIKE '%int%'
				AND `COLUMN_KEY` = 'PRI';
		SET SQL_EXP = CONCAT('ALTER TABLE `', (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA())), '`.`', TABLE_NAME_ARGUMENT, '` MODIFY COLUMN `', PRIMARY_KEY_COLUMN_NAME, '` ', PRIMARY_KEY_TYPE, ' NOT NULL AUTO_INCREMENT;');
		SET @SQL_EXP = SQL_EXP;
		PREPARE SQL_EXP_EXECUTE FROM @SQL_EXP;
		EXECUTE SQL_EXP_EXECUTE;
		DEALLOCATE PREPARE SQL_EXP_EXECUTE;
	END IF;
END //
DELIMITER ;

ALTER TABLE `Compra` DROP FOREIGN KEY `FK_Compra_FormaPagamento_FormaPagamentoId`;

ALTER TABLE `CompraCompartilhada` DROP FOREIGN KEY `FK_CompraCompartilhada_Compra_CompraId`;

ALTER TABLE `FORNECEDORES` DROP FOREIGN KEY `FK_FORNECEDORES_ENDERECOS_EnderecoId`;

ALTER TABLE `PRODUTOS` DROP FOREIGN KEY `FK_PRODUTOS_Categoria_CategoriaId`;

ALTER TABLE `FORNECEDORES` DROP INDEX `IX_FORNECEDORES_EnderecoId`;

CALL POMELO_BEFORE_DROP_PRIMARY_KEY(NULL, 'FormaPagamento');
ALTER TABLE `FormaPagamento` DROP PRIMARY KEY;

CALL POMELO_BEFORE_DROP_PRIMARY_KEY(NULL, 'CompraCompartilhada');
ALTER TABLE `CompraCompartilhada` DROP PRIMARY KEY;

CALL POMELO_BEFORE_DROP_PRIMARY_KEY(NULL, 'Categoria');
ALTER TABLE `Categoria` DROP PRIMARY KEY;

ALTER TABLE `FORNECEDORES` DROP COLUMN `EnderecoId`;

ALTER TABLE `FormaPagamento` RENAME `FORMAPAGAMENTO`;

ALTER TABLE `CompraCompartilhada` RENAME `COMPRACOMPARTILHADA`;

ALTER TABLE `Categoria` RENAME `CATEGORIA`;

ALTER TABLE `COMPRACOMPARTILHADA` RENAME INDEX `IX_CompraCompartilhada_CompraId` TO `IX_COMPRACOMPARTILHADA_CompraId`;

ALTER TABLE `FORMAPAGAMENTO` MODIFY COLUMN `NomeFormaPagamento` varchar(100) NOT NULL DEFAULT '';

ALTER TABLE `FORMAPAGAMENTO` MODIFY COLUMN `Ativo` bit NOT NULL;

ALTER TABLE `ENDERECOS` ADD `DataCriacao` datetime(6) NOT NULL DEFAULT '0001-01-01 00:00:00';

ALTER TABLE `ENDERECOS` ADD `DataModificacao` datetime(6) NOT NULL DEFAULT '0001-01-01 00:00:00';

ALTER TABLE `ENDERECOS` ADD `FornecedorID` char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE `ENDERECOS` ADD `UsuarioCriacao` varchar(100) NULL;

ALTER TABLE `ENDERECOS` ADD `UsuarioModificacao` varchar(100) NULL;

ALTER TABLE `COMPRACOMPARTILHADA` MODIFY COLUMN `UsuariosCompartilhados` varchar(100) NOT NULL DEFAULT '';

ALTER TABLE `CATEGORIA` MODIFY COLUMN `NomeCategoria` varchar(100) NOT NULL DEFAULT '';

ALTER TABLE `CATEGORIA` MODIFY COLUMN `Ativo` bit NOT NULL;

ALTER TABLE `FORMAPAGAMENTO` ADD CONSTRAINT `PK_FORMAPAGAMENTO` PRIMARY KEY (`Id`);
CALL POMELO_AFTER_ADD_PRIMARY_KEY(NULL, 'FORMAPAGAMENTO', 'Id');

ALTER TABLE `COMPRACOMPARTILHADA` ADD CONSTRAINT `PK_COMPRACOMPARTILHADA` PRIMARY KEY (`Id`);
CALL POMELO_AFTER_ADD_PRIMARY_KEY(NULL, 'COMPRACOMPARTILHADA', 'Id');

ALTER TABLE `CATEGORIA` ADD CONSTRAINT `PK_CATEGORIA` PRIMARY KEY (`Id`);
CALL POMELO_AFTER_ADD_PRIMARY_KEY(NULL, 'CATEGORIA', 'Id');

CREATE UNIQUE INDEX `IX_ENDERECOS_FornecedorID` ON `ENDERECOS` (`FornecedorID`);

ALTER TABLE `Compra` ADD CONSTRAINT `FK_Compra_FORMAPAGAMENTO_FormaPagamentoId` FOREIGN KEY (`FormaPagamentoId`) REFERENCES `FORMAPAGAMENTO` (`Id`) ON DELETE RESTRICT;

ALTER TABLE `COMPRACOMPARTILHADA` ADD CONSTRAINT `FK_COMPRACOMPARTILHADA_Compra_CompraId` FOREIGN KEY (`CompraId`) REFERENCES `Compra` (`Id`) ON DELETE RESTRICT;

ALTER TABLE `ENDERECOS` ADD CONSTRAINT `FK_ENDERECOS_FORNECEDORES_FornecedorID` FOREIGN KEY (`FornecedorID`) REFERENCES `FORNECEDORES` (`Id`) ON DELETE RESTRICT;

ALTER TABLE `PRODUTOS` ADD CONSTRAINT `FK_PRODUTOS_CATEGORIA_CategoriaId` FOREIGN KEY (`CategoriaId`) REFERENCES `CATEGORIA` (`Id`) ON DELETE RESTRICT;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210725181132_RelacaoEnderecoFornecedor', '5.0.1');

DROP PROCEDURE `POMELO_BEFORE_DROP_PRIMARY_KEY`;

DROP PROCEDURE `POMELO_AFTER_ADD_PRIMARY_KEY`;

COMMIT;

START TRANSACTION;

DROP PROCEDURE IF EXISTS `POMELO_BEFORE_DROP_PRIMARY_KEY`;
DELIMITER //
CREATE PROCEDURE `POMELO_BEFORE_DROP_PRIMARY_KEY`(IN `SCHEMA_NAME_ARGUMENT` VARCHAR(255), IN `TABLE_NAME_ARGUMENT` VARCHAR(255))
BEGIN
	DECLARE HAS_AUTO_INCREMENT_ID TINYINT(1);
	DECLARE PRIMARY_KEY_COLUMN_NAME VARCHAR(255);
	DECLARE PRIMARY_KEY_TYPE VARCHAR(255);
	DECLARE SQL_EXP VARCHAR(1000);
	SELECT COUNT(*)
		INTO HAS_AUTO_INCREMENT_ID
		FROM `information_schema`.`COLUMNS`
		WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
			AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
			AND `Extra` = 'auto_increment'
			AND `COLUMN_KEY` = 'PRI'
			LIMIT 1;
	IF HAS_AUTO_INCREMENT_ID THEN
		SELECT `COLUMN_TYPE`
			INTO PRIMARY_KEY_TYPE
			FROM `information_schema`.`COLUMNS`
			WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
				AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
				AND `COLUMN_KEY` = 'PRI'
			LIMIT 1;
		SELECT `COLUMN_NAME`
			INTO PRIMARY_KEY_COLUMN_NAME
			FROM `information_schema`.`COLUMNS`
			WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
				AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
				AND `COLUMN_KEY` = 'PRI'
			LIMIT 1;
		SET SQL_EXP = CONCAT('ALTER TABLE `', (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA())), '`.`', TABLE_NAME_ARGUMENT, '` MODIFY COLUMN `', PRIMARY_KEY_COLUMN_NAME, '` ', PRIMARY_KEY_TYPE, ' NOT NULL;');
		SET @SQL_EXP = SQL_EXP;
		PREPARE SQL_EXP_EXECUTE FROM @SQL_EXP;
		EXECUTE SQL_EXP_EXECUTE;
		DEALLOCATE PREPARE SQL_EXP_EXECUTE;
	END IF;
END //
DELIMITER ;

DROP PROCEDURE IF EXISTS `POMELO_AFTER_ADD_PRIMARY_KEY`;
DELIMITER //
CREATE PROCEDURE `POMELO_AFTER_ADD_PRIMARY_KEY`(IN `SCHEMA_NAME_ARGUMENT` VARCHAR(255), IN `TABLE_NAME_ARGUMENT` VARCHAR(255), IN `COLUMN_NAME_ARGUMENT` VARCHAR(255))
BEGIN
	DECLARE HAS_AUTO_INCREMENT_ID INT(11);
	DECLARE PRIMARY_KEY_COLUMN_NAME VARCHAR(255);
	DECLARE PRIMARY_KEY_TYPE VARCHAR(255);
	DECLARE SQL_EXP VARCHAR(1000);
	SELECT COUNT(*)
		INTO HAS_AUTO_INCREMENT_ID
		FROM `information_schema`.`COLUMNS`
		WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
			AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
			AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
			AND `COLUMN_TYPE` LIKE '%int%'
			AND `COLUMN_KEY` = 'PRI';
	IF HAS_AUTO_INCREMENT_ID THEN
		SELECT `COLUMN_TYPE`
			INTO PRIMARY_KEY_TYPE
			FROM `information_schema`.`COLUMNS`
			WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
				AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
				AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
				AND `COLUMN_TYPE` LIKE '%int%'
				AND `COLUMN_KEY` = 'PRI';
		SELECT `COLUMN_NAME`
			INTO PRIMARY_KEY_COLUMN_NAME
			FROM `information_schema`.`COLUMNS`
			WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
				AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
				AND `COLUMN_NAME` = COLUMN_NAME_ARGUMENT
				AND `COLUMN_TYPE` LIKE '%int%'
				AND `COLUMN_KEY` = 'PRI';
		SET SQL_EXP = CONCAT('ALTER TABLE `', (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA())), '`.`', TABLE_NAME_ARGUMENT, '` MODIFY COLUMN `', PRIMARY_KEY_COLUMN_NAME, '` ', PRIMARY_KEY_TYPE, ' NOT NULL AUTO_INCREMENT;');
		SET @SQL_EXP = SQL_EXP;
		PREPARE SQL_EXP_EXECUTE FROM @SQL_EXP;
		EXECUTE SQL_EXP_EXECUTE;
		DEALLOCATE PREPARE SQL_EXP_EXECUTE;
	END IF;
END //
DELIMITER ;

ALTER TABLE `Compra` DROP FOREIGN KEY `FK_Compra_FORMAPAGAMENTO_FormaPagamentoId`;

ALTER TABLE `Compra` DROP FOREIGN KEY `FK_Compra_FORNECEDORES_FornecedorId`;

ALTER TABLE `COMPRACOMPARTILHADA` DROP FOREIGN KEY `FK_COMPRACOMPARTILHADA_Compra_CompraId`;

ALTER TABLE `ENDERECOS` DROP FOREIGN KEY `FK_ENDERECOS_FORNECEDORES_FornecedorID`;

ALTER TABLE `ItmCompra` DROP FOREIGN KEY `FK_ItmCompra_Compra_CompraId`;

ALTER TABLE `COMPRACOMPARTILHADA` DROP INDEX `IX_COMPRACOMPARTILHADA_CompraId`;

CALL POMELO_BEFORE_DROP_PRIMARY_KEY(NULL, 'Compra');
ALTER TABLE `Compra` DROP PRIMARY KEY;

ALTER TABLE `Compra` RENAME `COMPRAR`;

ALTER TABLE `ENDERECOS` CHANGE `FornecedorID` `FornecedorId` char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE `ENDERECOS` RENAME INDEX `IX_ENDERECOS_FornecedorID` TO `IX_ENDERECOS_FornecedorId`;

ALTER TABLE `COMPRAR` RENAME INDEX `IX_Compra_FornecedorId` TO `IX_COMPRAR_FornecedorId`;

ALTER TABLE `COMPRAR` RENAME INDEX `IX_Compra_FormaPagamentoId` TO `IX_COMPRAR_FormaPagamentoId`;

ALTER TABLE `COMPRAR` ADD CONSTRAINT `PK_COMPRAR` PRIMARY KEY (`Id`);
CALL POMELO_AFTER_ADD_PRIMARY_KEY(NULL, 'COMPRAR', 'Id');

CREATE INDEX `IX_COMPRACOMPARTILHADA_CompraId` ON `COMPRACOMPARTILHADA` (`CompraId`);

ALTER TABLE `COMPRACOMPARTILHADA` ADD CONSTRAINT `FK_COMPRACOMPARTILHADA_COMPRAR_CompraId` FOREIGN KEY (`CompraId`) REFERENCES `COMPRAR` (`Id`) ON DELETE RESTRICT;

ALTER TABLE `COMPRAR` ADD CONSTRAINT `FK_COMPRAR_FORMAPAGAMENTO_FormaPagamentoId` FOREIGN KEY (`FormaPagamentoId`) REFERENCES `FORMAPAGAMENTO` (`Id`) ON DELETE RESTRICT;

ALTER TABLE `COMPRAR` ADD CONSTRAINT `FK_COMPRAR_FORNECEDORES_FornecedorId` FOREIGN KEY (`FornecedorId`) REFERENCES `FORNECEDORES` (`Id`) ON DELETE RESTRICT;

ALTER TABLE `ENDERECOS` ADD CONSTRAINT `FK_ENDERECOS_FORNECEDORES_FornecedorId` FOREIGN KEY (`FornecedorId`) REFERENCES `FORNECEDORES` (`Id`) ON DELETE RESTRICT;

ALTER TABLE `ItmCompra` ADD CONSTRAINT `FK_ItmCompra_COMPRAR_CompraId` FOREIGN KEY (`CompraId`) REFERENCES `COMPRAR` (`Id`) ON DELETE RESTRICT;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20211231205718_ajusteModeloCompra', '5.0.1');

DROP PROCEDURE `POMELO_BEFORE_DROP_PRIMARY_KEY`;

DROP PROCEDURE `POMELO_AFTER_ADD_PRIMARY_KEY`;

COMMIT;

START TRANSACTION;

ALTER TABLE `ItmCompra` ADD `Ativo` tinyint(1) NOT NULL DEFAULT FALSE;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20220612224801_ItemAtivo', '5.0.1');

COMMIT;

